Repository Diptenusarkar/html.org.in, pull requests merged in 2023-10, with the labels that each got.

#83 ]Fix] : HomePage Card Issue
  Website/Style/web/main_d485f_v1.css
  Website/Style/web/main_post_d485f_v1.css
Labels: hacktoberfest-accepted

#110 first commit
  html/html_block_and_inline_elements/404.html
  html/html_block_and_inline_elements/index.html
Labels: Under Review, Need To fix, HPLNA

#124 Update README.md
  README.md
Labels: documentation
